import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'stop gaining weight',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className="flex flex-col items-center justify-center h-screen">
        <div>{children}</div>
      </body>
    </html>
  )
}
