'use client'
import AuthContext from './context/AuthContext'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Record Weight',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className="flex flex-col items-center justify-center h-screen">
        {' '}
        <AuthContext>
          <div>{children}</div>
        </AuthContext>
      </body>
    </html>
  )
}
